<a href="https://colab.research.google.com/github/AsmaeKarmouchi/AI-interview-prep/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Libraries for Data Analysis**



**1.Exploring the Fundamentals of NumPy Arrays in Python**



In [1]:
import numpy as np

rocket_fuel_tanks = np.array([[6, 4], [5, 7]])

print("Rocket Fuel Tanks:\n", rocket_fuel_tanks)

print("\nSize of Rocket Fuel Tanks:", rocket_fuel_tanks.size)
print("Shape of Rocket Fuel Tanks:", rocket_fuel_tanks.shape)
print("Data type of Rocket Fuel Tanks:", rocket_fuel_tanks.dtype)

Rocket Fuel Tanks:
 [[6 4]
 [5 7]]

Size of Rocket Fuel Tanks: 4
Shape of Rocket Fuel Tanks: (2, 2)
Data type of Rocket Fuel Tanks: int64


In [ ]:
import numpy as np

# Assume we have four solar panels  2D numpy array with 2 rows.
grid_power = np.array([[500, 700], [700, 900]])

# Print the array
print("\nSpaceship Grid Power:", grid_power)

# Display the size, shape, and data type of our array
print("Size of Spaceship Grid Power Array:", grid_power.size)
print("Shape of Spaceship Grid Power Array:", grid_power.shape)
print("Data type of Spaceship Grid Power Array:", grid_power.dtype)

**2.Unpacking Data Selection Techniques in NumPy Arrays**

In [2]:
import numpy as np

# Create a NumPy array of wage per hour
wages_per_hour = np.array([14, 16, 20, 22, 25, 28, 30, 35, 38, 40, 45, 50])

# Select wages greater than 30 per hour
print(wages_per_hour[wages_per_hour > 30])
#-------------------------------------------------------

# Create a NumPy array of ages
ages = np.array([15, 18, 16, 19, 36, 34, 27, 21, 23, 25])

# Select adult(s age under 30 years
adults = ages[(ages > 18) & (ages < 30)]
print("Adults:", adults)
#-------------------------------------------------------

# Create a NumPy array
weight = np.array([12, 15, 11, 9, 23, 10, 12, 20, 25, 25, 8, 15, 4])

# TODO: Select weights greater than 20 or less than 10

weight_analysis = weight[(weight > 20) | (weight < 10)]

print(weight_analysis)

[35 38 40 45 50]


In [1]:
import numpy as np

badges = np.array([12, 14, 15, 20, 32, 33, 40, 42])

# TODO: Using a condition-based selection, filter badges that has even number lower than 33
f = badges[(badges < 33) & (badges % 2 == 0)][:3]
# TODO: Print the filtered numbers.
print(f)

[12 14 20]


**Arithmetic Operations with NumPy Arrays**
- Two arrays of the same shape can undergo basic arithmetic operations.
- NumPy's Universal Functions (also called ufuncs) perform element-wise operations on arrays, including mathematical functions like sin, cos, log, and sqrt.
- NumPy allows the application of a custom function to each element of the array separately by transforming the target function with np.vectorize

In [2]:
import numpy as np

# Function to calculate percentage marks
def percentage_calc(percentage_marks):
    return (percentage_marks * 100) / 75

# Array of raw marks
raw_marks = np.array([35, 48, 60, 72, 75])

# Compute percentage using our function
percentage_calc = np.vectorize(percentage_calc)
percentage_marks = percentage_calc(raw_marks)

print("Raw Marks: ", raw_marks)
print("Percentage Marks: ", percentage_marks)

Raw Marks:  [35 48 60 72 75]
Percentage Marks:  [ 46.66666667  64.          80.          96.         100.        ]


In [3]:
import numpy as np

# Function to calculate the discount price
def discount_price(price):
    if price > 350:
        return price - (price * 0.30)  # 30% discount for prices > 350
    else:
        return price - (price * 0.20)  # 20% discount otherwise

# Array of original prices
prices = np.array([100, 200, 300, 400, 500])

# Apply the function to the whole array
discounted_price = np.vectorize(discount_price)
discounted_prices = discounted_price(prices)

# Display results
print("Original Prices: ", prices)
print("Discounted Prices: ", discounted_prices)


Original Prices:  [100 200 300 400 500]
Discounted Prices:  [ 80. 160. 240. 280. 350.]
